# asset filename = generic input
1P=x
2P=y
3P=rb
4P=lb
1K=a
2K=b
3K=rt
4K=lt
1A=lsb
2A=rsb
3P_4P=lb_rb
3K_4K=lt_rt
stick=dp
stick_up=dp_up
stick_down=dp_down
stick_left=dp_left
stick_right=dp_right
stick_up_left=dp_up_left
stick_up_right=dp_up_right
stick_down_left=dp_down_left
stick_down_right=dp_down_right
stick_left_right=dp_left_right
stick_up_down=dp_up_down
stick=ls
stick_up=ls_up
stick_down=ls_down
stick_right=ls_right
stick_left=ls_left
stick_down_right=ls_down_right
stick_down_left=ls_down_left
stick_up_right=ls_up_right
stick_up_left=ls_up_left
stick_left_right=ls_left_right
stick_up_down=ls_up_down
stick_cw=ls_cw
stick_ccw=ls_ccw
player_1=menu
insert_coin=view
trackball=rs
trackball_up=rs_up
trackball_down=rs_down
trackball_left=rs_left
trackball_right=rs_right
trackball_up_left=rs_up_left
trackball_up_right=rs_up_right
trackball_down_left=rs_down_left
trackball_down_right=rs_down_right
trackball_left_right=rs_left_right
trackball_up_down=rs_up_down
spinner_cw=rs_cw
spinner_ccw=rs_ccw


