# asset filename = generic input
X=Y
Space=A
C=B
R=X
RightShift=view
Enter=menu
Q=lb
G=rb
ChevronLeftRight=lb_rb
Divide=lt
Enter=rt
BracketLeftRight=lt_rt
UpDownLeftRight=dp
Up=dp_up
Down=dp_down
Left=dp_left
Right=dp_right
UpLeft=dp_up_left
DownRight=dp_down_right
DownLeft=dp_down_left
UpRight=dp_up_right
UpDown=dp_up_down
LeftRight=dp_left_right
WSAD=ls
R=ls_cw
Q=ls_ccw
W=ls_up
S=ls_down
A=ls_left
D=ls_right
WA=ls_up_left
SD=ls_down_right
SA=ls_down_left
WD=ls_up_right
AD=ls_left_right
WS=ls_up_down
Shift=lsb
8246=rs
9=rs_cw
7=rs_ccw
8=rs_up
2=rs_down
4=rs_left
6=rs_right
84=rs_up_left
62=rs_down_right
42=rs_down_left
86=rs_up_right
46=rs_left_right
82=rs_up_down
V=rsb
F1=home
