# asset filename = generic input
back=view
start=menu
left_trackpad=dp
left_trackpad_up=dp_up
left_trackpad_down=dp_down
left_trackpad_left=dp_left
left_trackpad_right=dp_right
left_trackpad_left_right=dp_left_right
left_trackpad_up_down=dp_up_down
left_trackpad_up_left=dp_up_left
left_trackpad_up_right=dp_up_right
left_trackpad_down_left=dp_down_left
left_trackpad_down_right=dp_down_right
right_trackpad=rs
right_trackpad_click=rsb
right_trackpad_cw=rs_cw
right_trackpad_ccw=rs_ccw
right_trackpad_down=rs_down
right_trackpad_up=rs_up
right_trackpad_left=rs_left
right_trackpad_right=rs_right
right_trackpad_up_down=rs_up_down
right_trackpad_left_right=rs_left_right
right_trackpad_up_left=rs_up_left
right_trackpad_up_right=rs_up_right
right_trackpad_down_left=rs_down_left
right_trackpad_down_right=rs_down_right
